"""Tests for the engine-side AcroForm read/fill/flatten (Phase 2l — the CLI
parity implementation; the GUI path is renderer-side pdf-lib)."""

import re
import os

import pikepdf
import pytest
from pikepdf import Dictionary, Name

from engine.extract_text import extract_text
from engine.forms import FF_MULTISELECT, fill_form_fields, read_form_fields, reset_form_fields

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
# Generated by pdf-lib (the GUI's own library) — the exact input shape the
# renderer path produces/handles: text, multiline text, checkbox, /Opt-indexed
# radio group, dropdown. Cross-tool input for the engine implementation.
PDFLIB_FORM = os.path.join(FIXTURES_DIR, "form-pdflib.pdf")

# The vendored fallback fonts (Rust `get_edit_font_path` at runtime); FC1's
# Unicode-appearance tests need them and skip when the bundle isn't provisioned.
FONTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "resources", "fonts"
)
_HAS_FONTS = os.path.isfile(os.path.join(FONTS_DIR, "LiberationSans-Regular.ttf"))


def _make_raw_form(path: str) -> None:
    """A form built with raw pikepdf objects: inherited /FT via a parent
    field, a dotted name, an /Opt dropdown with [export, display] pairs, and
    an AcroForm-level /DA — the inheritance shapes the walker must handle."""
    pdf = pikepdf.new()
    page = pdf.add_blank_page(page_size=(400, 400))
    helv = pdf.make_indirect(
        Dictionary(Type=Name.Font, Subtype=Name.Type1, BaseFont=Name.Helvetica, Encoding=Name.WinAnsiEncoding)
    )

    def widget(rect):
        return pdf.make_indirect(
            Dictionary(
                Type=Name.Annot,
                Subtype=Name.Widget,
                Rect=rect,
                F=4,
                P=page.obj,
            )
        )

    # Parent "person" carries /FT /Tx that the kids inherit; kids are fields
    # with their own /T (dotted names) that are ALSO merged widgets.
    first = widget([40, 340, 200, 364])
    first["/T"] = pikepdf.String("first")
    last = widget([40, 300, 200, 324])
    last["/T"] = pikepdf.String("last")
    person = pdf.make_indirect(
        Dictionary(T=pikepdf.String("person"), FT=Name.Tx, Kids=pikepdf.Array([first, last]))
    )
    first["/Parent"] = person
    last["/Parent"] = person

    # Read-only text field.
    locked = widget([40, 260, 200, 284])
    locked["/T"] = pikepdf.String("locked")
    locked["/FT"] = Name.Tx
    locked["/Ff"] = 1

    # Dropdown with [export, display] /Opt pairs.
    combo = widget([40, 220, 200, 244])
    combo["/T"] = pikepdf.String("country")
    combo["/FT"] = Name.Ch
    combo["/Ff"] = 1 << 17
    combo["/Opt"] = pikepdf.Array(
        [
            pikepdf.Array([pikepdf.String("US"), pikepdf.String("United States")]),
            pikepdf.Array([pikepdf.String("CA"), pikepdf.String("Canada")]),
        ]
    )

    page.obj["/Annots"] = pikepdf.Array([first, last, locked, combo])
    pdf.Root["/AcroForm"] = pdf.make_indirect(
        Dictionary(
            Fields=pikepdf.Array([person, locked, combo]),
            DA=pikepdf.String("/Helv 0 Tf 0 g"),
            DR=Dictionary(Font=Dictionary(Helv=helv)),
        )
    )
    pdf.save(path)
    pdf.close()


class TestReadFormFields:
    def test_pdflib_fixture_enumeration(self):
        r = read_form_fields(PDFLIB_FORM)
        assert r["has_xfa"] is False
        by_name = {f["name"]: f for f in r["fields"]}
        assert by_name["applicant.name"]["type"] == "text"
        assert by_name["applicant.name"]["multiline"] is False
        assert by_name["notes"]["multiline"] is True
        assert by_name["agree"]["type"] == "checkbox"
        assert by_name["agree"]["value"] is False
        assert by_name["color"]["type"] == "radio"
        assert by_name["color"]["options"] == ["red", "blue"]
        assert by_name["size"]["type"] == "dropdown"
        assert by_name["size"]["options"] == ["small", "medium", "large"]

    def test_raw_fixture_inheritance_and_dotted_names(self, tmp_dir):
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        r = read_form_fields(src)
        by_name = {f["name"]: f for f in r["fields"]}
        # /FT inherited from the parent; names are dotted.
        assert by_name["person.first"]["type"] == "text"
        assert by_name["person.last"]["type"] == "text"
        assert by_name["locked"]["read_only"] is True
        assert by_name["country"]["options"] == ["United States", "Canada"]

    def test_no_form(self, sample_pdf):
        r = read_form_fields(sample_pdf)
        assert r["fields"] == [] and r["count"] == 0

    def test_fc3_widgets_carry_page_and_rect(self, tmp_dir):
        # FC3: each field reports its widgets' 0-based page + normalized rect —
        # incl. the NESTED typed-terminal kids (person.first/last), which the
        # engine already enumerates (S6) and now list WITH geometry (the shape
        # the on-canvas overlay needs when the read routes through the engine).
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        by = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by["person.first"]["widgets"] == [
            {"page": 0, "rect": [40.0, 340.0, 200.0, 364.0], "hidden": False}
        ]
        assert by["person.last"]["widgets"] == [
            {"page": 0, "rect": [40.0, 300.0, 200.0, 324.0], "hidden": False}
        ]
        assert all("widgets" in f for f in by.values())

    def test_fc3_widget_page_index_across_pages(self, tmp_dir):
        # A widget on the SECOND page reports page index 1 — resolved via the
        # page's /Annots even though the widget carries no /P.
        out = os.path.join(tmp_dir, "multi.pdf")
        pdf = pikepdf.new()
        pdf.add_blank_page(page_size=(300, 300))
        p1 = pdf.add_blank_page(page_size=(300, 300))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[10, 20, 110, 44],
                FT=Name.Tx, T=pikepdf.String("f2"),
            )
        )
        p1.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]))
        pdf.save(out)
        pdf.close()
        f2 = next(f for f in read_form_fields(out)["fields"] if f["name"] == "f2")
        assert f2["widgets"] == [{"page": 1, "rect": [10.0, 20.0, 110.0, 44.0], "hidden": False}]

    def test_fc4_multiselect_optionlist(self, tmp_dir):
        # FC4: a LIST value on a multi-select list box stores /V as the export
        # ARRAY + /I as the sorted selected indices, regenerates an appearance,
        # and reads back the full selection. A single string still works.
        src = os.path.join(tmp_dir, "ms.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(400, 400))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 300, 200, 380],
                FT=Name("/Ch"), T=pikepdf.String("colors"), Ff=FF_MULTISELECT,
                Opt=pikepdf.Array([
                    pikepdf.Array([pikepdf.String("r"), pikepdf.String("Red")]),
                    pikepdf.Array([pikepdf.String("g"), pikepdf.String("Green")]),
                    pikepdf.Array([pikepdf.String("b"), pikepdf.String("Blue")]),
                ]),
                P=page.obj,
            )
        )
        page.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(
            Fields=pikepdf.Array([w]), DA=pikepdf.String("/Helv 10 Tf 0 g")
        )
        pdf.save(src)
        pdf.close()
        out = os.path.join(tmp_dir, "mso.pdf")
        assert fill_form_fields(src, out, {"colors": ["Red", "Blue"]})["filled"] == 1
        with pikepdf.open(out) as p:
            f = p.Root["/AcroForm"]["/Fields"][0]
            assert [str(x) for x in f["/V"]] == ["r", "b"]  # exports
            assert [int(x) for x in f["/I"]] == [0, 2]  # sorted /Opt indices
            assert "/AP" in f  # appearance regenerated
        assert read_form_fields(out)["fields"][0]["value"] == ["r", "b"]
        # A single string still selects one item (backward compatible).
        out2 = os.path.join(tmp_dir, "mso2.pdf")
        fill_form_fields(src, out2, {"colors": "Green"})
        with pikepdf.open(out2) as p:
            assert str(p.Root["/AcroForm"]["/Fields"][0]["/V"]) == "g"

    def test_fc4_multiselect_rejects_bad_option(self, tmp_dir):
        # An element that is not an option is refused (atomically), listing it.
        src = os.path.join(tmp_dir, "ms2.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(400, 400))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 300, 200, 380],
                FT=Name("/Ch"), T=pikepdf.String("colors"), Ff=FF_MULTISELECT,
                Opt=pikepdf.Array([pikepdf.String("Red"), pikepdf.String("Blue")]),
                P=page.obj,
            )
        )
        page.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]), DA=pikepdf.String("/Helv 10 Tf 0 g"))
        pdf.save(src)
        pdf.close()
        out = os.path.join(tmp_dir, "ms2o.pdf")
        with pytest.raises(ValueError, match="no option"):
            fill_form_fields(src, out, {"colors": ["Red", "Purple"]})
        assert not os.path.exists(out)

    def test_fc4_multiselect_promotes_ff_flag(self, tmp_dir):
        # Gauntlet HIGH: writing 2+ selections onto a NON-multiselect list box
        # sets the /Ff MultiSelect bit (else the array /V is spec-non-conformant,
        # which pdf-lib never produces — it auto-promotes).
        src = os.path.join(tmp_dir, "nf.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(400, 400))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 300, 200, 380],
                FT=Name("/Ch"), T=pikepdf.String("c"), Ff=0,  # NOT multiselect
                Opt=pikepdf.Array([pikepdf.String("Red"), pikepdf.String("Green"), pikepdf.String("Blue")]),
                P=page.obj,
            )
        )
        page.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]), DA=pikepdf.String("/Helv 10 Tf 0 g"))
        pdf.save(src)
        pdf.close()
        out = os.path.join(tmp_dir, "nfo.pdf")
        fill_form_fields(src, out, {"c": ["Red", "Blue"]})
        with pikepdf.open(out) as p:
            assert int(p.Root["/AcroForm"]["/Fields"][0].get("/Ff", 0)) & FF_MULTISELECT

    def test_fc4_empty_value_clears_choice_selection(self, tmp_dir):
        # Gauntlet CRITICAL follow-on: an EMPTY value CLEARS a choice selection
        # (pdf-lib's field.clear()) instead of erroring "no option ''". A GUI
        # that lets the user deselect a radio/dropdown depends on this.
        out1 = os.path.join(tmp_dir, "c1.pdf")
        fill_form_fields(PDFLIB_FORM, out1, {"color": "blue", "size": "medium"})
        b1 = {f["name"]: f["value"] for f in read_form_fields(out1)["fields"]}
        assert b1["color"] == "blue" and b1["size"] == "medium"
        out2 = os.path.join(tmp_dir, "c2.pdf")
        fill_form_fields(out1, out2, {"color": "", "size": ""})  # deselect both
        b2 = {f["name"]: f["value"] for f in read_form_fields(out2)["fields"]}
        assert b2["color"] == ""  # radio de-selected → /Off
        assert b2["size"] == ""  # dropdown de-selected → /V dropped

    def test_fc3_widget_in_two_pages_annots_not_misattributed(self, tmp_dir):
        # Gauntlet MEDIUM: the SAME widget object listed in TWO pages' /Annots
        # (malformed third-party input) must NOT be silently pinned to one page.
        # With no /P it reports page None (unplaced) — the scan never guesses.
        out = os.path.join(tmp_dir, "dup.pdf")
        pdf = pikepdf.new()
        p0 = pdf.add_blank_page(page_size=(300, 300))
        p1 = pdf.add_blank_page(page_size=(300, 300))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[1, 2, 3, 4],
                FT=Name.Tx, T=pikepdf.String("dup"),
            )
        )
        p0.obj["/Annots"] = pikepdf.Array([w])
        p1.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]))
        pdf.save(out)
        pdf.close()
        dup = next(f for f in read_form_fields(out)["fields"] if f["name"] == "dup")
        assert dup["widgets"] == [{"page": None, "rect": [1.0, 2.0, 3.0, 4.0], "hidden": False}]

    def test_fc3_ambiguous_widget_resolves_via_P(self, tmp_dir):
        # The ambiguous (two-/Annots) widget's spec-authoritative /P disambiguates
        # to page 1 rather than falling to None.
        out = os.path.join(tmp_dir, "dupP.pdf")
        pdf = pikepdf.new()
        p0 = pdf.add_blank_page(page_size=(300, 300))
        p1 = pdf.add_blank_page(page_size=(300, 300))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[1, 2, 3, 4],
                FT=Name.Tx, T=pikepdf.String("dup"), P=p1.obj,
            )
        )
        p0.obj["/Annots"] = pikepdf.Array([w])
        p1.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]))
        pdf.save(out)
        pdf.close()
        dup = next(f for f in read_form_fields(out)["fields"] if f["name"] == "dup")
        assert dup["widgets"] == [{"page": 1, "rect": [1.0, 2.0, 3.0, 4.0], "hidden": False}]

    def test_fc3_rect_normalized(self, tmp_dir):
        # A /Rect in a non-standard corner order normalizes to [x0,y0,x1,y1].
        out = os.path.join(tmp_dir, "rot.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[110, 44, 10, 20],
                FT=Name.Tx, T=pikepdf.String("r"),
            )
        )
        page.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]))
        pdf.save(out)
        pdf.close()
        assert read_form_fields(out)["fields"][0]["widgets"] == [
            {"page": 0, "rect": [10.0, 20.0, 110.0, 44.0], "hidden": False}
        ]

    def test_fc4b_widget_hidden_flag(self, tmp_dir):
        # FC4b: a widget with /F Hidden (bit 2) or NoView (bit 6) reports
        # hidden=True — the overlay offers no input where the raster shows
        # nothing. AF_HIDDEN = 1<<1 = 2.
        out = os.path.join(tmp_dir, "hid.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))
        w = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[10, 20, 110, 44],
                FT=Name.Tx, T=pikepdf.String("h"), F=2, P=page.obj,
            )
        )
        page.obj["/Annots"] = pikepdf.Array([w])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([w]))
        pdf.save(out)
        pdf.close()
        assert read_form_fields(out)["fields"][0]["widgets"][0]["hidden"] is True

    def test_fc4b_radio_widget_maps_to_its_option(self, tmp_dir):
        # FC4b: each radio widget reports the DISPLAY option its on-state
        # selects — /Opt-indexed on-states ('0'/'1') map through /Opt, so the
        # overlay knows which option a widget commits.
        out = os.path.join(tmp_dir, "radio.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))

        def _w(state, rect):
            n = Dictionary()
            n[state] = Dictionary()
            n["/Off"] = Dictionary()
            return pdf.make_indirect(
                Dictionary(
                    Type=Name.Annot, Subtype=Name.Widget, Rect=rect, P=page.obj,
                    AP=Dictionary(N=n), AS=Name("/Off"),
                )
            )

        w0 = _w("/0", [10, 200, 25, 215])
        w1 = _w("/1", [10, 170, 25, 185])
        field = pdf.make_indirect(
            Dictionary(
                FT=Name.Btn, Ff=(1 << 15), T=pikepdf.String("color"),
                Kids=pikepdf.Array([w0, w1]),
                Opt=pikepdf.Array([pikepdf.String("Red"), pikepdf.String("Blue")]),
            )
        )
        w0["/Parent"] = field
        w1["/Parent"] = field
        page.obj["/Annots"] = pikepdf.Array([w0, w1])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([field]))
        pdf.save(out)
        pdf.close()
        f = next(f for f in read_form_fields(out)["fields"] if f["name"] == "color")
        assert f["type"] == "radio"
        assert [w.get("option") for w in f["widgets"]] == ["Red", "Blue"]

    def test_fc4b_signature_filled_flag(self, tmp_dir):
        # FC4b: a signature field reports filled=True only when /V is present.
        out = os.path.join(tmp_dir, "sig.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))
        empty = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[10, 200, 110, 240],
                FT=Name.Sig, T=pikepdf.String("sig-empty"), P=page.obj,
            )
        )
        done = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[10, 100, 110, 140],
                FT=Name.Sig, T=pikepdf.String("sig-done"), V=Dictionary(), P=page.obj,
            )
        )
        page.obj["/Annots"] = pikepdf.Array([empty, done])
        pdf.Root["/AcroForm"] = Dictionary(Fields=pikepdf.Array([empty, done]))
        pdf.save(out)
        pdf.close()
        by = {f["name"]: f for f in read_form_fields(out)["fields"]}
        assert by["sig-empty"]["type"] == "signature" and by["sig-empty"]["filled"] is False
        assert by["sig-done"]["filled"] is True


class TestFillFormFields:
    def test_fill_every_type_and_reread(self, tmp_dir):
        out = os.path.join(tmp_dir, "filled.pdf")
        r = fill_form_fields(
            PDFLIB_FORM,
            out,
            {
                "applicant.name": "Jason Q. Tester",
                "notes": "wrap this text across the box\nsecond paragraph",
                "agree": True,
                "color": "blue",
                "size": "medium",
            },
        )
        assert r["filled"] == 5 and r["flattened"] is False
        back = read_form_fields(out)
        values = {f["name"]: f["value"] for f in back["fields"]}
        assert values["applicant.name"] == "Jason Q. Tester"
        assert values["agree"] is True
        assert values["color"] == "blue"
        assert values["size"] == "medium"

        with pikepdf.open(out) as pdf:
            # Widgets carry regenerated appearances with the value text, and
            # /AS states match the radio selection.
            annots = list(pdf.pages[0].obj["/Annots"])
            texts = [a for a in annots if a.get("/FT") == Name.Tx or (a.get("/Parent") is not None and a["/Parent"].get("/FT") == Name.Tx)]
            assert any(b"Jason Q. Tester" in a["/AP"]["/N"].read_bytes() for a in annots if a.get("/AP") is not None and isinstance(a["/AP"].get("/N"), pikepdf.Stream))
            # The blue radio widget is on; the red one is /Off.
            radio_states = [str(a.get("/AS")) for a in annots if a.get("/AS") is not None]
            assert "/1" in radio_states  # blue == index 1 (pdf-lib /Opt-indexed)
            # NeedAppearances is not set.
            assert "/NeedAppearances" not in pdf.Root["/AcroForm"]

    def test_option_pairs_fill_by_display_or_export(self, tmp_dir):
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        out = os.path.join(tmp_dir, "f1.pdf")
        fill_form_fields(src, out, {"country": "Canada"})
        with pikepdf.open(out) as pdf:
            fields = pdf.Root["/AcroForm"]["/Fields"]
            combo = next(f for f in fields if str(f.get("/T", "")) == "country")
            assert str(combo["/V"]) == "CA"  # export stored, display accepted
        out2 = os.path.join(tmp_dir, "f2.pdf")
        fill_form_fields(src, out2, {"country": "US"})  # export accepted too
        with pikepdf.open(out2) as pdf:
            combo = next(f for f in pdf.Root["/AcroForm"]["/Fields"] if str(f.get("/T", "")) == "country")
            assert str(combo["/V"]) == "US"

    def test_validation_reports_all_problems_and_writes_nothing(self, tmp_dir):
        out = os.path.join(tmp_dir, "nope.pdf")
        with pytest.raises(ValueError) as exc:
            fill_form_fields(
                PDFLIB_FORM,
                out,
                {"missing": "x", "agree": "maybe", "color": "green"},
            )
        msg = str(exc.value)
        assert "no such field: missing" in msg
        assert "checkbox agree needs true/false" in msg
        assert "radio color has no option 'green'" in msg
        assert not os.path.exists(out)

    def test_read_only_refused(self, tmp_dir):
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        out = os.path.join(tmp_dir, "nope.pdf")
        with pytest.raises(ValueError, match="read-only"):
            fill_form_fields(src, out, {"locked": "x"})
        assert not os.path.exists(out)

    def test_non_winansi_value_fails_closed(self, tmp_dir):
        # Caught at VALIDATION time now (review round: the all-problems
        # contract includes encodability), with the WinAnsi message. Without a
        # font_dir there is no fallback, so a non-WinAnsi value is still refused.
        out = os.path.join(tmp_dir, "nope.pdf")
        with pytest.raises(ValueError, match="WinAnsi"):
            fill_form_fields(PDFLIB_FORM, out, {"applicant.name": "日本語テキスト"})
        assert not os.path.exists(out)

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_fc1_unicode_value_embeds_font_and_round_trips(self, tmp_dir):
        # FC1 (§I.0 S3): a Cyrillic+Greek value (outside WinAnsi) fills via an
        # EMBEDDED Type0/Identity-H font when font_dir is given, instead of
        # being refused; the value round-trips and the appearance shows a
        # hex-encoded string against the embedded font.
        out = os.path.join(tmp_dir, "uni.pdf")
        val = "Привет Ελληνικά мир"
        r = fill_form_fields(PDFLIB_FORM, out, {"applicant.name": val}, font_dir=FONTS_DIR)
        assert r["filled"] == 1
        back = {f["name"]: f["value"] for f in read_form_fields(out)["fields"]}
        assert back["applicant.name"] == val
        with pikepdf.open(out) as pdf:
            uni_streams = []
            for a in pdf.pages[0].obj["/Annots"]:
                ap = a.get("/AP")
                n = ap.get("/N") if ap is not None else None
                if not isinstance(n, pikepdf.Stream):
                    continue
                res = n.get("/Resources")
                fonts = res.get("/Font") if res is not None else None
                if fonts is None:
                    continue
                if any(str(fonts[k].get("/Subtype")) == "/Type0" for k in fonts.keys()):
                    uni_streams.append(n)
            assert len(uni_streams) == 1  # exactly applicant.name's appearance
            body = uni_streams[0].read_bytes()
            assert b"/TxU" in body  # the embedded-font resource name
            assert b"> Tj" in body  # a hex string show, not a WinAnsi (...) Tj

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_fc1_cjk_fills_via_the_cjk_face(self, tmp_dir):
        # T5 INVERSION (was: refusal). The value-driven CJK step lands a
        # CJK form value on Noto Sans CJK when the bundle carries it; the
        # refusal survives only when the CJK faces are absent.
        cjk_present = os.path.isfile(os.path.join(FONTS_DIR, "NotoSansCJKsc-Regular.otf"))
        out = os.path.join(tmp_dir, "cjk.pdf")
        if not cjk_present:
            with pytest.raises(ValueError, match="no available font can render"):
                fill_form_fields(PDFLIB_FORM, out, {"applicant.name": "日本語"}, font_dir=FONTS_DIR)
            assert not os.path.exists(out)
            return
        fill_form_fields(PDFLIB_FORM, out, {"applicant.name": "日本語"}, font_dir=FONTS_DIR)
        fields = {f["name"]: f for f in read_form_fields(out)["fields"]}
        assert fields["applicant.name"]["value"] == "日本語"

    def test_fc1_unicode_without_font_dir_refused(self, tmp_dir):
        # Without a font_dir the non-WinAnsi value is refused with the
        # no-fallback message (not a silent partial).
        out = os.path.join(tmp_dir, "no.pdf")
        with pytest.raises(ValueError, match="no fallback font is available"):
            fill_form_fields(PDFLIB_FORM, out, {"applicant.name": "Привет"}, font_dir="")
        assert not os.path.exists(out)

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_fc1_multiline_unicode_wraps(self, tmp_dir):
        # The multiline 'notes' field wraps a long Cyrillic value using the
        # embedded font's OWN metrics (width_em) — multiple baselines emitted.
        out = os.path.join(tmp_dir, "ml.pdf")
        r = fill_form_fields(PDFLIB_FORM, out, {"notes": ("Привет мир " * 10).strip()}, font_dir=FONTS_DIR)
        assert r["filled"] == 1
        with pikepdf.open(out) as pdf:
            body = next(
                a["/AP"]["/N"].read_bytes()
                for a in pdf.pages[0].obj["/Annots"]
                if a.get("/AP") is not None and isinstance(a["/AP"].get("/N"), pikepdf.Stream)
                and (a["/AP"]["/N"].get("/Resources") or {}).get("/Font") is not None
                and any(
                    str(a["/AP"]["/N"]["/Resources"]["/Font"][k].get("/Subtype")) == "/Type0"
                    for k in a["/AP"]["/N"]["/Resources"]["/Font"].keys()
                )
            )
            # More than one show → the text wrapped onto multiple lines.
            assert body.count(b"> Tj") >= 2

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_fc1_unicode_with_control_chars_fills(self, tmp_dir):
        # Gauntlet HIGH regression: a non-WinAnsi value containing layout-only
        # control chars (\n, \r\n, \t) is validated OK (they're excluded from
        # coverage) and must FILL — not crash inside build_fallback_font, whose
        # own coverage gate would reject the control chars. All variants the
        # reviewer reproduced:
        cases = {
            "notes": "Привет\nмир",        # multiline field + LF
            "applicant.name": "Привет\tмир",  # single-line field + TAB
        }
        for field, val in cases.items():
            out = os.path.join(tmp_dir, f"ctl_{field.replace('.', '_')}.pdf")
            r = fill_form_fields(PDFLIB_FORM, out, {field: val}, font_dir=FONTS_DIR)
            assert r["filled"] == 1
            # The value round-trips through /V verbatim (unchanged by the
            # appearance normalisation, which is display-only).
            back = {f["name"]: f["value"] for f in read_form_fields(out)["fields"]}
            assert back[field] == val
        # A CRLF multi-paragraph value in the multiline field respects the break
        # (two baselines) and doesn't leave a stray CR in the drawn glyphs.
        out = os.path.join(tmp_dir, "crlf.pdf")
        r = fill_form_fields(
            PDFLIB_FORM, out, {"notes": "Привет\r\nмир земной"}, font_dir=FONTS_DIR
        )
        assert r["filled"] == 1

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_fc1_broad_control_chars_render(self, tmp_dir):
        # S4-gauntlet analog for forms: a Unicode value with a control char
        # beyond \n\r\t (VT, Unicode LINE SEPARATOR) now FILLS (flattened to
        # space) instead of being refused in validation.
        out = os.path.join(tmp_dir, "ctlbroad.pdf")
        r = fill_form_fields(
            PDFLIB_FORM, out, {"applicant.name": "При\x0bвет" + chr(0x2028) + "мир"}, font_dir=FONTS_DIR
        )
        assert r["filled"] == 1

    def test_auto_size_and_inherited_da(self, tmp_dir):
        # The raw fixture's AcroForm /DA is "/Helv 0 Tf" — auto-size. The
        # appearance stream must carry a concrete positive size.
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        out = os.path.join(tmp_dir, "auto.pdf")
        fill_form_fields(src, out, {"person.first": "A reasonably long value to size"})
        with pikepdf.open(out) as pdf:
            annots = pdf.pages[0].obj["/Annots"]
            ap = next(
                a["/AP"]["/N"].read_bytes()
                for a in annots
                if a.get("/AP") is not None and isinstance(a["/AP"].get("/N"), pikepdf.Stream)
            )
            import re

            m = re.search(rb"/Helv ([\d.]+) Tf", ap)
            assert m is not None and float(m.group(1)) > 0

    def test_in_place_fill(self, tmp_dir):
        import shutil

        working = os.path.join(tmp_dir, "working.pdf")
        shutil.copy(PDFLIB_FORM, working)
        fill_form_fields(working, working, {"applicant.name": "In Place"})
        assert read_form_fields(working)["fields"][0]["value"] == "In Place"


class TestFlatten:
    def test_flatten_bakes_values_into_page_content(self, tmp_dir):
        out = os.path.join(tmp_dir, "flat.pdf")
        r = fill_form_fields(
            PDFLIB_FORM,
            out,
            {"applicant.name": "FLATVALUE", "agree": True, "color": "red", "size": "large"},
            flatten=True,
        )
        assert r["flattened"] is True
        # Independent, non-circular: pdfminer extracts the value from PAGE
        # CONTENT (the appearance became real content), and the form is gone.
        text = extract_text(out)["text"]
        assert "FLATVALUE" in text
        assert "large" in text
        with pikepdf.open(out) as pdf:
            assert "/AcroForm" not in pdf.Root
            assert pdf.pages[0].obj.get("/Annots") is None
        assert read_form_fields(out)["count"] == 0

    def test_hidden_widget_not_stamped_but_removed(self, tmp_dir):
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        # Hide person.first's widget (AF_HIDDEN), then flatten with a value.
        with pikepdf.open(src) as pdf:
            annots = pdf.pages[0].obj["/Annots"]
            annots[0]["/F"] = 2
            pdf.save(src + ".h.pdf")
        out = os.path.join(tmp_dir, "flat.pdf")
        fill_form_fields(src + ".h.pdf", out, {"person.first": "GHOST"}, flatten=True)
        text = extract_text(out)["text"]
        assert "GHOST" not in text  # hidden → not stamped
        with pikepdf.open(out) as pdf:
            assert pdf.pages[0].obj.get("/Annots") is None  # but still removed


class TestXfaParity:
    def test_xfa_detected_and_stripped(self, tmp_dir):
        src = os.path.join(tmp_dir, "xfa.pdf")
        with pikepdf.open(PDFLIB_FORM) as pdf:
            pdf.Root["/AcroForm"]["/XFA"] = pikepdf.Array([])
            pdf.save(src)
        assert read_form_fields(src)["has_xfa"] is True
        out = os.path.join(tmp_dir, "out.pdf")
        r = fill_form_fields(src, out, {"applicant.name": "x"})
        assert r["xfa_stripped"] is True
        with pikepdf.open(out) as pdf:
            assert "/XFA" not in pdf.Root["/AcroForm"]


class TestReviewFindings2l:
    def test_missing_da_font_substitutes_honestly_and_reports(self, tmp_dir):
        # Review HIGH: /DA names /TiRo, /DR lacks it. The fallback must NOT
        # register Helvetica under the name TiRo (wrong face claimed, shared
        # /DR polluted for every field referencing it). It renders AND names
        # Helvetica, locally only, and the result reports the substitution.
        src = os.path.join(tmp_dir, "tiro.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))
        helv = pdf.make_indirect(
            Dictionary(Type=Name.Font, Subtype=Name.Type1, BaseFont=Name.Helvetica, Encoding=Name.WinAnsiEncoding)
        )
        fld = pdf.make_indirect(
            Dictionary(
                Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 200, 260, 224],
                T=pikepdf.String("styled"), FT=Name.Tx,
                DA=pikepdf.String("/TiRo 12 Tf 0 g"),
            )
        )
        page.obj["/Annots"] = pikepdf.Array([fld])
        pdf.Root["/AcroForm"] = pdf.make_indirect(
            Dictionary(Fields=pikepdf.Array([fld]), DR=Dictionary(Font=Dictionary(Helv=helv)))
        )
        pdf.save(src)
        pdf.close()

        out = os.path.join(tmp_dir, "out.pdf")
        r = fill_form_fields(src, out, {"styled": "Hello"})
        assert r["fonts_substituted"] == ["styled"]
        with pikepdf.open(out) as pdf2:
            widget = pdf2.pages[0].obj["/Annots"][0]
            ap = widget["/AP"]["/N"].read_bytes()
            assert b"/Helv " in ap and b"/TiRo" not in ap  # honest naming
            res_fonts = widget["/AP"]["/N"]["/Resources"]["/Font"]
            assert "/Helv" in res_fonts and "/TiRo" not in res_fonts
            # Shared /DR unpolluted: no fake TiRo entry anywhere.
            dr_fonts = pdf2.Root["/AcroForm"]["/DR"]["/Font"]
            assert "/TiRo" not in dr_fonts

    def test_all_encoding_problems_listed_together(self, tmp_dir):
        # Review: two non-WinAnsi values must BOTH appear in one error.
        out = os.path.join(tmp_dir, "nope.pdf")
        with pytest.raises(ValueError) as exc:
            fill_form_fields(
                PDFLIB_FORM, out,
                {"applicant.name": "日本語", "notes": "кириллица"},
            )
        msg = str(exc.value)
        assert "applicant.name" in msg and "notes" in msg
        assert not os.path.exists(out)

    def test_multiwidget_checkbox_with_differing_on_states(self, tmp_dir):
        # Review: two widget kids of ONE checkbox with different on-state
        # names ("Yes"/"On") must BOTH light when checked.
        src = os.path.join(tmp_dir, "mw.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))

        def state_ap(on_name):
            n = Dictionary()
            on_stream = pdf.make_stream(b"q Q")
            off_stream = pdf.make_stream(b"q Q")
            n[Name("/" + on_name)] = on_stream
            n[Name("/Off")] = off_stream
            return Dictionary(N=n)

        k1 = pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 200, 56, 216], AP=state_ap("Yes"))
        )
        k2 = pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 160, 56, 176], AP=state_ap("On"))
        )
        parent = pdf.make_indirect(
            Dictionary(T=pikepdf.String("dual"), FT=Name.Btn, Kids=pikepdf.Array([k1, k2]))
        )
        k1["/Parent"] = parent
        k2["/Parent"] = parent
        page.obj["/Annots"] = pikepdf.Array([k1, k2])
        pdf.Root["/AcroForm"] = pdf.make_indirect(Dictionary(Fields=pikepdf.Array([parent])))
        pdf.save(src)
        pdf.close()

        out = os.path.join(tmp_dir, "out.pdf")
        fill_form_fields(src, out, {"dual": True})
        with pikepdf.open(out) as pdf2:
            annots = pdf2.pages[0].obj["/Annots"]
            states = sorted(str(a["/AS"]) for a in annots)
            assert states == ["/On", "/Yes"]  # each widget lit via ITS state

        out2 = os.path.join(tmp_dir, "out2.pdf")
        fill_form_fields(src, out2, {"dual": False})
        with pikepdf.open(out2) as pdf2:
            assert all(str(a["/AS"]) == "/Off" for a in pdf2.pages[0].obj["/Annots"])

    def test_bare_widget_kid_with_stray_ft_not_duplicated(self, tmp_dir):
        # Review: a /T-less kid carrying its own /FT must be treated as a
        # WIDGET of the parent, never a duplicate field that shadows siblings
        # in the fill's name->field map.
        src = os.path.join(tmp_dir, "stray.pdf")
        pdf = pikepdf.new()
        page = pdf.add_blank_page(page_size=(300, 300))
        named_kid = pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 200, 200, 224],
                       T=pikepdf.String("inner"), FT=Name.Tx)
        )
        bare1 = pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 160, 200, 184], FT=Name.Tx)
        )
        bare2 = pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=[40, 120, 200, 144], FT=Name.Tx)
        )
        parent = pdf.make_indirect(
            Dictionary(T=pikepdf.String("grp"), FT=Name.Tx,
                       Kids=pikepdf.Array([named_kid, bare1, bare2]))
        )
        for k in (named_kid, bare1, bare2):
            k["/Parent"] = parent
        page.obj["/Annots"] = pikepdf.Array([named_kid, bare1, bare2])
        pdf.Root["/AcroForm"] = pdf.make_indirect(
            Dictionary(Fields=pikepdf.Array([parent]), DA=pikepdf.String("/Helv 10 Tf 0 g"))
        )
        pdf.save(src)
        pdf.close()

        names = [f["name"] for f in read_form_fields(src)["fields"]]
        assert names.count("grp") == 1 and "grp.inner" in names  # no duplicates
        out = os.path.join(tmp_dir, "out.pdf")
        fill_form_fields(src, out, {"grp": "both widgets"})
        with pikepdf.open(out) as pdf2:
            annots = pdf2.pages[0].obj["/Annots"]
            with_value = [
                a for a in annots
                if a.get("/AP") is not None
                and isinstance(a["/AP"].get("/N"), pikepdf.Stream)
                and b"both widgets" in a["/AP"]["/N"].read_bytes()
            ]
            assert len(with_value) == 2  # BOTH bare widgets got the appearance


def _make_button_form(path: str) -> None:
    """Text field WITH /DV, checkbox with /DV on, and pushbuttons carrying
    the /A kinds the F8 overlay classifies (URI / ResetForm / JavaScript)."""
    pdf = pikepdf.new()
    page = pdf.add_blank_page(page_size=(400, 400))
    helv = pdf.make_indirect(
        Dictionary(Type=Name.Font, Subtype=Name.Type1, BaseFont=Name.Helvetica, Encoding=Name.WinAnsiEncoding)
    )

    def widget(rect):
        return pdf.make_indirect(
            Dictionary(Type=Name.Annot, Subtype=Name.Widget, Rect=rect, F=4, P=page.obj)
        )

    name = widget([40, 340, 200, 364])
    name["/T"] = pikepdf.String("name")
    name["/FT"] = Name.Tx
    name["/V"] = pikepdf.String("typed value")
    name["/DV"] = pikepdf.String("default value")

    agree = widget([40, 300, 60, 320])
    agree["/T"] = pikepdf.String("agree")
    agree["/FT"] = Name.Btn
    agree["/V"] = Name("/Off")
    agree["/DV"] = Name("/Yes")
    agree["/AP"] = Dictionary(
        N=Dictionary(
            Yes=pdf.make_stream(b"0 g 0 0 20 20 re f"),
            Off=pdf.make_stream(b""),
        )
    )

    def push(rect, tname, action):
        b = widget(rect)
        b["/T"] = pikepdf.String(tname)
        b["/FT"] = Name.Btn
        b["/Ff"] = 1 << 16  # pushbutton
        b["/A"] = action
        return b

    uri_btn = push([40, 260, 120, 284], "visit", Dictionary(S=Name.URI, URI=pikepdf.String("https://example.com/x")))
    reset_btn = push(
        [40, 220, 120, 244], "resetall",
        Dictionary(S=pikepdf.Name("/ResetForm")),
    )
    js_btn = push(
        [40, 180, 120, 204], "compute",
        Dictionary(S=pikepdf.Name("/JavaScript"), JS=pikepdf.String("app.alert(1)")),
    )
    reset_scoped = push(
        [40, 140, 120, 164], "resetname",
        Dictionary(S=pikepdf.Name("/ResetForm"), Fields=pikepdf.Array([pikepdf.String("name")])),
    )

    page.obj["/Annots"] = pikepdf.Array([name, agree, uri_btn, reset_btn, js_btn, reset_scoped])
    pdf.Root["/AcroForm"] = pdf.make_indirect(
        Dictionary(
            Fields=pikepdf.Array([name, agree, uri_btn, reset_btn, js_btn, reset_scoped]),
            DA=pikepdf.String("/Helv 0 Tf 0 g"),
            DR=Dictionary(Font=Dictionary(Helv=helv)),
        )
    )
    pdf.save(path)
    pdf.close()


class TestButtonActionsAndReset:
    """F8 — pushbutton /A classification + the ResetForm engine op."""

    def test_read_reports_button_actions(self, tmp_dir):
        src = os.path.join(tmp_dir, "b.pdf")
        _make_button_form(src)
        by_name = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by_name["visit"]["action"] == {"kind": "uri", "uri": "https://example.com/x"}
        assert by_name["resetall"]["action"] == {"kind": "reset", "fields": None, "exclude": False}
        assert by_name["resetname"]["action"] == {
            "kind": "reset", "fields": ["name"], "exclude": False,
        }
        assert by_name["compute"]["action"] == {"kind": "javascript"}
        assert "action" not in by_name["name"]  # only buttons carry it

    def test_reset_restores_dv_and_clears(self, tmp_dir):
        src = os.path.join(tmp_dir, "b.pdf")
        _make_button_form(src)
        # Dirty the fields first.
        fill_form_fields(src, src, {"name": "user typed", "agree": True})
        r = reset_form_fields(src, src)
        assert r["reset"] == 2
        by_name = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by_name["name"]["value"] == "default value"  # /DV restored
        assert by_name["agree"]["value"] is True  # /DV /Yes restored

    def test_reset_scoped_and_excluded(self, tmp_dir):
        src = os.path.join(tmp_dir, "b.pdf")
        _make_button_form(src)
        fill_form_fields(src, src, {"name": "user typed", "agree": False})
        # Scope to "name" only: agree stays as filled.
        reset_form_fields(src, src, fields=["name"])
        by_name = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by_name["name"]["value"] == "default value"
        assert by_name["agree"]["value"] is False
        # Exclude "name": everything BUT name resets.
        fill_form_fields(src, src, {"name": "again", "agree": False})
        reset_form_fields(src, src, fields=["name"], exclude=True)
        by_name = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by_name["name"]["value"] == "again"
        assert by_name["agree"]["value"] is True

    def test_reset_without_dv_clears(self, tmp_dir):
        src = os.path.join(tmp_dir, "raw.pdf")
        _make_raw_form(src)
        fill_form_fields(src, src, {"person.first": "Ada", "country": "Canada"})
        r = reset_form_fields(src, src)
        assert r["reset"] >= 2
        by_name = {f["name"]: f for f in read_form_fields(src)["fields"]}
        assert by_name["person.first"]["value"] == ""
        assert by_name["country"]["value"] == ""

    def test_reset_empty_scope_is_a_result(self, tmp_dir):
        src = os.path.join(tmp_dir, "b.pdf")
        _make_button_form(src)
        out = os.path.join(tmp_dir, "o.pdf")
        r = reset_form_fields(src, out, fields=["no.such.field"])
        assert r["reset"] == 0
        assert os.path.isfile(out)  # the output exists even with nothing to do


def _drawn_gids(pdf_path, content: str):
    """The GLYPH ids the content stream actually draws, resolved through the
    embedded font's /CIDToGIDMap.

    9.T25: a shaped subset addresses glyphs by CID, not by glyph id — several
    CIDs may point at ONE glyph, which is how a base glyph spells one cluster
    under one code and a different cluster under another. A test that wants to
    know which GLYPHS were drawn therefore has to go through the map;
    comparing codes to source glyph ids only worked before the map existed."""
    import pikepdf

    codes = [int(h, 16) for h in re.findall(r"<([0-9a-fA-F]{4})>", content)]
    table = None
    with pikepdf.open(pdf_path) as pdf:
        for obj in pdf.objects:
            if not isinstance(obj, pikepdf.Dictionary):
                continue
            if str(obj.get("/Subtype", "")) != "/CIDFontType2":
                continue
            c2g = obj.get("/CIDToGIDMap")
            if c2g is not None and not isinstance(c2g, pikepdf.Name):
                table = bytes(c2g.read_bytes())
                break
    if table is None:
        return codes  # /Identity: the code IS the glyph id
    return [
        (table[c * 2] << 8) | table[c * 2 + 1]
        for c in codes
        if c * 2 + 1 < len(table)
    ]


def _contains_run(haystack, needle) -> bool:
    n = len(needle)
    return any(haystack[i : i + n] == needle for i in range(len(haystack) - n + 1))


class TestRightToLeftFill:
    """9.T25c — right-to-left form values fill instead of being refused."""

    AR = "مرحبا بالعالم"
    HE = "שלום עולם"

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_arabic_value_fills(self, tmp_dir):
        rtl_present = os.path.isfile(os.path.join(FONTS_DIR, "IBMPlexSansArabic-Regular.ttf"))
        out = os.path.join(tmp_dir, "ar.pdf")
        if not rtl_present:
            # The refusal survives on an unprovisioned bundle — honestly.
            with pytest.raises(ValueError, match="no available font can render"):
                fill_form_fields(PDFLIB_FORM, out, {"applicant.name": self.AR},
                                 font_dir=FONTS_DIR)
            return
        fill_form_fields(PDFLIB_FORM, out, {"applicant.name": self.AR}, font_dir=FONTS_DIR)
        fields = {f["name"]: f for f in read_form_fields(out)["fields"]}
        # The stored VALUE is always logical — /V is a string, not a drawing.
        assert fields["applicant.name"]["value"] == self.AR

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_hebrew_value_fills(self, tmp_dir):
        rtl_present = os.path.isfile(os.path.join(FONTS_DIR, "NotoSansHebrew-Regular.ttf"))
        if not rtl_present:
            pytest.skip("RTL faces not provisioned")
        out = os.path.join(tmp_dir, "he.pdf")
        fill_form_fields(PDFLIB_FORM, out, {"applicant.name": self.HE}, font_dir=FONTS_DIR)
        fields = {f["name"]: f for f in read_form_fields(out)["fields"]}
        assert fields["applicant.name"]["value"] == self.HE

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_the_APPEARANCE_is_reordered_and_shaped(self, tmp_dir):
        # /V holds logical text either way, so only the drawn APPEARANCE can
        # show that the reorder and the shaping happened: an unshaped
        # emission would be one `Tj` of isolated forms in logical order.
        from fontTools.ttLib import TTFont

        from engine import shaping

        face = os.path.join(FONTS_DIR, "IBMPlexSansArabic-Regular.ttf")
        if not os.path.isfile(face):
            pytest.skip("RTL faces not provisioned")
        out = os.path.join(tmp_dir, "ap.pdf")
        fill_form_fields(PDFLIB_FORM, out, {"applicant.name": "مرحبا"}, font_dir=FONTS_DIR)
        with pikepdf.open(out) as pdf:
            # The embedded-font resource name marks the appearance this fill
            # wrote; /AP /N can be a sub-dictionary on other widgets.
            streams = [
                bytes(o.read_bytes())
                for o in pdf.objects
                if isinstance(o, pikepdf.Stream) and b"/TxU" in bytes(o.read_bytes())
            ]
        body = b"".join(streams).decode("latin-1")
        gid_of = {n: i for i, n in enumerate(TTFont(face, lazy=True).getGlyphOrder())}
        joined = [gid_of[n] for n in shaping.shape(face, "مرحبا").glyph_names]
        isolated = [gid_of[shaping.shape(face, c).glyph_names[0]] for c in reversed("مرحبا")]
        assert joined != isolated  # the premise
        drawn = _drawn_gids(out, body)
        assert _contains_run(drawn, joined)
        assert not _contains_run(drawn, isolated)

    @pytest.mark.skipif(not _HAS_FONTS, reason="bundled fonts not provisioned")
    def test_multiline_rtl_wraps(self, tmp_dir):
        face = os.path.join(FONTS_DIR, "IBMPlexSansArabic-Regular.ttf")
        if not os.path.isfile(face):
            pytest.skip("RTL faces not provisioned")
        out = os.path.join(tmp_dir, "ml.pdf")
        value = ("مرحبا بالعالم " * 8).strip()
        r = fill_form_fields(PDFLIB_FORM, out, {"notes": value}, font_dir=FONTS_DIR)
        assert r["filled"] == 1
        fields = {f["name"]: f for f in read_form_fields(out)["fields"]}
        assert fields["notes"]["value"] == value
