// Scan enhancement, end to end through the real panel and the real engine.
//
// The two arms that are worth proving in a browser rather than in pytest are
// the ones whose evidence is a NUMBER the user reads and a page the viewer
// then draws: the measured skew, and the orientation that lands as the page's
// own /Rotate. Both fixtures are built by `tests/fixtures/make_enhance_scans.py`
// and checked in, so the angle the panel reports has a ground truth (2.75
// degrees) and the turn it applies has an expected answer (90).
//
// It runs against the WORKING copy through `performOperation` — the standard
// snapshot → engine → reload → UPDATE_FILE flow — so what these assertions
// exercise is the same undoable path a user gets, not a direct engine call.
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { expect } from '@wdio/globals';
import { PDFDocument } from 'pdf-lib';
import {
  waitForHarness,
  openByPaths,
  setView,
  setActiveOp,
  closeAllFiles,
  getState,
  invokeAppCommand,
  saveActiveAs,
} from '../support/harness.js';

const PY_FIXTURES = resolve(__dirname, '..', '..', 'tests', 'fixtures');
const SKEW = resolve(PY_FIXTURES, 'scan-skew.pdf');
const SIDEWAYS = resolve(PY_FIXTURES, 'scan-sideways.pdf');

/** The angle `make_enhance_scans.py` builds `scan-skew.pdf` at. */
const SKEW_DEGREES = 2.75;
/** A measurement decodes, segments and OSDs the page — seconds, not millis. */
const MEASURE_TIMEOUT = 90_000;

/** Wait for the panel to have measured, then hand back what it says.
 *
 * Readiness is read off the PRESENCE of the change line, which the panel
 * renders only once it has found a scan — not off its English, which the
 * language-switch spec shares an app session with. */
async function report(): Promise<Record<string, string>> {
  await browser.waitUntil(
    async () => $('[data-testid="scanenhance-changing"]').isExisting(),
    { timeout: MEASURE_TIMEOUT, timeoutMsg: 'the panel never measured a scanned page' },
  );
  const out: Record<string, string> = {};
  for (const id of [
    'scanenhance-scans',
    'scanenhance-changing',
    'scanenhance-deskew-row',
    'scanenhance-despeckle-row',
    'scanenhance-whiten-row',
    'scanenhance-rotate-row',
  ]) {
    const el = $(`[data-testid="${id}"]`);
    out[id] = (await el.isExisting()) ? await el.getText() : '';
  }
  return out;
}

/** Run the enhancement and wait for it to finish, failing loudly on a refusal.
 *
 * The finished status is matched on a DIGIT rather than on English: the suite
 * shares one app session and spec 103 drives the language switch, so an
 * assertion on the word "Enhanced" would be a locale-order dependency. The
 * error case is read off the bar's own error styling, which is what the
 * catalog-driven `isPanelErrorText` sets — not off the text either. */
async function applyAndWait(): Promise<void> {
  const button = $('[data-testid="scanenhance-apply"]');
  await browser.waitUntil(async () => button.isEnabled(), {
    timeout: MEASURE_TIMEOUT,
    timeoutMsg: 'the Apply button never enabled — the preview found nothing to do',
  });
  await button.click();
  const bar = $('[data-testid="status-bar"]');
  await browser.waitUntil(
    async () => {
      const cls = (await bar.getAttribute('class')) ?? '';
      if (cls.includes('bg-red-900')) {
        throw new Error(`the enhancement refused: ${await bar.getText()}`);
      }
      return /\d/.test(await bar.getText());
    },
    { timeout: MEASURE_TIMEOUT, timeoutMsg: 'the enhancement never reported a page count' },
  );
}

describe('scan enhancement', () => {
  let tmp: string;

  before(async () => {
    tmp = mkdtempSync(resolve(tmpdir(), 'spectra-e2e-enhance-'));
    await waitForHarness();
  });

  after(async () => {
    await closeAllFiles();
    if (tmp && existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
  });

  it('Scan & OCR now seats the Scan Enhancement pane', async function () {
    this.timeout(120_000);
    if (!existsSync(SKEW)) {
      // Generated by tests/fixtures/make_enhance_scans.py and checked in; a
      // tree without it has nothing to say about scan enhancement.
      this.skip();
      return;
    }
    await closeAllFiles();
    await openByPaths([SKEW]);
    expect(await invokeAppCommand('tools.open.ocr')).toBe(true);
    const state = await getState();
    expect(state.activeOp).toBe('scanenhance');
  });

  it('measures the page’s real skew and straightens it', async function () {
    this.timeout(300_000);
    if (!existsSync(SKEW)) {
      this.skip();
      return;
    }
    await closeAllFiles();
    await openByPaths([SKEW]);
    // `setActiveOp` seats the panel; `setView('operations')` is what opens the
    // dock that MOUNTS it (the 111-image-codecs lesson).
    await setView('operations');
    await setActiveOp('scanenhance');

    const before = await report();
    expect(before['scanenhance-scans']).toContain('1');
    // The number the whole feature is: the panel states the lean BEFORE
    // anything is rewritten, and it has to be the angle the fixture was built
    // at, to two decimals.
    const match = /(-?\d+[.,]\d+)/.exec(before['scanenhance-deskew-row']);
    if (!match) throw new Error(`no angle in "${before['scanenhance-deskew-row']}"`);
    expect(Math.abs(Number(match[1].replace(',', '.')) - SKEW_DEGREES)).toBeLessThanOrEqual(0.1);

    await applyAndWait();

    // The proof the correction landed: the panel re-measures the RELOADED
    // buffer and the lean is gone. A second run would find nothing to rotate.
    await browser.waitUntil(
      async () => {
        const row = $('[data-testid="scanenhance-deskew-row"]');
        return !(await row.isExisting());
      },
      { timeout: MEASURE_TIMEOUT, timeoutMsg: 'the page still reads as skewed after straightening' },
    );
  });

  it('turns a sideways scan upright, and the saved file carries the rotation', async function () {
    this.timeout(300_000);
    if (!existsSync(SIDEWAYS)) {
      this.skip();
      return;
    }
    await closeAllFiles();
    await openByPaths([SIDEWAYS]);
    await setView('operations');
    await setActiveOp('scanenhance');

    const before = await report();
    expect(before['scanenhance-rotate-row']).not.toBe('');

    await applyAndWait();

    const out = resolve(tmp, 'upright.pdf');
    await saveActiveAs(out);
    expect(existsSync(out)).toBe(true);
    const doc = await PDFDocument.load(readFileSync(out));
    // OSD is LOSSLESS: it writes the page's own /Rotate and no pixel moves.
    expect(doc.getPage(0).getRotation().angle).toBe(90);

    // And it is idempotent — an upright page reports no turn to make.
    await browser.waitUntil(
      async () => {
        const row = $('[data-testid="scanenhance-rotate-row"]');
        return !(await row.isExisting());
      },
      { timeout: MEASURE_TIMEOUT, timeoutMsg: 'the page still reads as turned after being righted' },
    );
  });

  it('refuses a born-digital page by name instead of pretending', async function () {
    this.timeout(180_000);
    const born = resolve(__dirname, '..', 'fixtures', 'sample.pdf');
    if (!existsSync(born)) {
      this.skip();
      return;
    }
    await closeAllFiles();
    await openByPaths([born]);
    await setView('operations');
    await setActiveOp('scanenhance');

    // Refused, and SAID SO per page — "nothing happened to page 4" must not be
    // a question the user has to guess the answer to.
    await browser.waitUntil(
      async () => $('[data-testid="scanenhance-refused"]').isExisting(),
      { timeout: MEASURE_TIMEOUT, timeoutMsg: 'a page set from text was not refused by name' },
    );
    // And no change line, because there is no scan in scope to change.
    expect(await $('[data-testid="scanenhance-changing"]').isExisting()).toBe(false);
    expect(await $('[data-testid="scanenhance-apply"]').isEnabled()).toBe(false);
  });
});
